### ISSUE TITLE
Crash with TConstruct (API change)

### ISSUE THREAD

**Issue by Thiana** [legendblade/CraftingHarmonics#151]
TConstruct decided to rewrite part of their public API... Leading to:

```
java.lang.NoSuchMethodError: slimeknights.tconstruct.library.TinkerRegistry.registerTableCasting(Lslimeknights/tconstruct/library/smeltery/CastingRecipe;)V
	at org.winterblade.minecraft.harmony.integration.ticon.ReflectedTinkerRegistry.addTableCast(ReflectedTinkerRegistry.java:93)
	at org.winterblade.minecraft.harmony.integration.ticon.operations.AddSmelteryTableCast.apply(AddSmelteryTableCast.java:41)
	at org.winterblade.minecraft.harmony.api.BasicOperation.runApply(BasicOperation.java:85)
	at org.winterblade.minecraft.harmony.OperationSet.apply(OperationSet.java:207)
	at org.winterblade.minecraft.harmony.CraftingHarmonicsMod.applySet(CraftingHarmonicsMod.java:187)
	at org.winterblade.minecraft.harmony.CraftingHarmonicsMod.applySets(CraftingHarmonicsMod.java:173)
	at org.winterblade.minecraft.harmony.CraftingHarmonicsMod.applyBaseSets(CraftingHarmonicsMod.java:335)
	at org.winterblade.minecraft.harmony.utility.EventHandler.onLoggedIn(EventHandler.java:57)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_184_EventHandler_onLoggedIn_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:565)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:228)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:260)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by legendblade** [comment]
@Thiana I'm putting this off until 1.5.7 since the version of TiCon this affects is currently Alpha; I'm going to go ahead and release 1.5.6 with what I have in it right now, and then 1.5.7 will follow shortly thereafter with the fix for this and #152.
