### ISSUE TITLE
Error logging into game with difficulty based set enabled

### ISSUE THREAD

**Issue by legendblade** [legendblade/CraftingHarmonics#27]

**Comment by legendblade** [comment]
Causes the following:

```
[15:42:41] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking memory connection
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:195) ~[ma.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:728) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148) ~[byn.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
	at net.minecraft.item.crafting.CraftingManager.func_82787_a(SourceFile:1227) ~[afv.class:?]
	at net.minecraft.inventory.ContainerPlayer.func_75130_a(ContainerPlayer.java:92) ~[abl.class:?]
	at net.minecraft.inventory.ContainerPlayer.<init>(ContainerPlayer.java:87) ~[abl.class:?]
	at net.minecraft.entity.player.EntityPlayer.<init>(EntityPlayer.java:154) ~[zj.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.<init>(EntityPlayerMP.java:140) ~[lr.class:?]
	at net.minecraft.server.management.PlayerList.func_148545_a(PlayerList.java:492) ~[mm.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:133) ~[md.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.func_73660_a(NetHandlerLoginServer.java:60) ~[md.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:286) ~[ek.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) ~[ma.class:?]
	... 5 more
```

This immediately after it tries to apply the recipe operations for the difficulty set.
